### ISSUE TITLE
Option for custom OprnAi endpoint

### ISSUE THREAD

**Issue by kmadaras** [MegaGrindStone/mcp-web-ui#3]
i host my own models with an OpenAI compatible endpoint using VLLM and would appreciate a configurable endpoint URL to be able to enable use of self hosted nfrastructure.  Can you please consider adding this as an option? 

Thanks!

**Comment by MegaGrindStone** [comment]
Latest commit already add this option. Now, you could set this in config:

```yaml
llm:
  provider: openai
  model: gpt-4o-2024-08-06
  apiKey: YOUR_API_KEY
  endpoint: https://custom.openai.endpoint # Replace this with your openai endpoint
```

I need to adjust a minor changes in README before shipping a new release, but you could use the latest commit to use this option.
