### ISSUE TITLE
Error when calling Anthropic API

### ISSUE THREAD

**Issue by mikaelmorvan** [MegaGrindStone/mcp-web-ui#5]
Hi,

I'm trying to use the mcp-web-ui and I've got this error when I send a message in the web ui

`error sending request: unexpected status code: 400, body: {"type":"error","error":{"type":"invalid_request_error","message":"stop_sequences: each stop sequence must be non-empty"}}, request: {"model":"claude-3-5-sonnet-20241022","messages":[{"role":"user","content":[{"type":"text","text":"liste les fichiers"}]}],"system":"You are a helpful assistant.","max_tokens":1000,"tools":[],"stream":true,"stop_sequences":["","\n"],"temperature":0.5,"top_k":40,"top_p":0.9}`

Any clue ?

Thanks
  Mikaël

**Comment by mikaelmorvan** [comment]
My current config

```yaml
port: 8080
logLevel: debug # Choose one of the following: debug, info, warn, error, default to info
logMode: text # Choose one of the following: json, text, default to text
systemPrompt: You are a helpful assistant.
titleGeneratorPrompt: Generate a title for this chat with only one sentence with maximum 5 words.
# Choose one of the following LLM providers: ollama, anthropic
llm:
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  parameters: # This is optional, and only used by some LLM providers.
    temperature: 0.5
    topP: 0.9
    topK: 40
    frequencyPenalty: 0.0
    presencePenalty: 0.0
    repetitionPenalty: 1.0
    minP: 0.0
    topA: 0.0
    seed: 0
    maxTokens: 1000
    logitBias: 
      dummyTokenID: 0.0
    logprobs: true
    topLogprobs: 10
    stop:
      - "\n"
      - "\n\n"
    includeReasoning: true
  # ollama
  host: http://localhost:11434 # Default to environment variable OLLAMA_HOST
  # anthropic
  apiKey: XXXXXX
  maxTokens: 1000

genTitleLLM: # Default to the same LLM as the main LLM
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  apiKey: XXXXXX
  maxTokens: 1000
  parameters: # This is optional, and only used by some LLM providers.
    temperature: 0.5
    topP: 0.9
    topK: 40
    frequencyPenalty: 0.0
    presencePenalty: 0.0
    repetitionPenalty: 1.0
    minP: 0.0
    topA: 0.0
    seed: 0
    maxTokens: 1000
    logprobs: true
    topLogprobs: 10
    stop:
      - "\n"
      - "\n\n"
    includeReasoning: true
# mcpSSEServers:
#   filesystem:
#     url: https://yoursseserver.com
#     maxPayloadSize: 1048576 # 1MB
mcpStdIOServers:
  filesystem:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "/home/mikaelmorvan/code/ppit"
```
