### ISSUE TITLE
Add Mistral endpoint in the documentation

### ISSUE THREAD

**Issue by mikaelmorvan** [MegaGrindStone/mcp-web-ui#6]
Hi,

For those who want to use Mistral LLM, it's possible without changing the source code. In fact Mistral API is fully compliant with OpenAi one so in the yaml file, just change the config as follow

```yaml
llm:
  # mistral
  apiKey: XXXXX
  endpoint: https://api.mistral.ai/v1
  model: mistral-large-latest
  provider: openai
  maxTokens: 1000
```

Mikaël
